# Generated by Django 5.1.6 on 2025-02-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingSystem', '0002_choice_question_user_vote_delete_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='votingSystem.question'),
        ),
    ]
